build:
  image: registry.salsa.debian.org/salsa-ci-team/ci-image-git-buildpackage:latest
  artifacts:
    paths:
    - "*.deb"
    expire_in: 1 day
  except:
    - tags
  script:
    - gitlab-ci-git-buildpackage-all
